# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=400, unique_for_date='publish'),
        ),
    ]
